### ISSUE TITLE
Decoding issue

### ISSUE THREAD

**Issue by dciug** [laserpants/hashids-haskell#12] opened 2021-03-25 17:51 UTC
This is the error:
`Web/Hashids.hs:(342,5)-(347,18): Non-exhaustive patterns in Just str@(lottery, tail)`

Version: 1.0.2.4

How I think it can be recreated:
Change the context value used by the decoder and try to call decode a previously valid encoding (that used the old context).

**Comment by joehealy** [comment] 2021-06-12 01:04
This can be caused by an invalid encoded string :(

**Comment by laserpants** [comment] 2022-01-18 12:54
This was addressed in https://github.com/laserpants/hashids-haskell/commit/5fc889c7da79c13a93ed85243bc9d53bafb4c414 and published as version `1.0.2.7` to Hackage. Please re-open if the issue still persists.

**Closed as completed by laserpants** 2022-01-18 12:54 UTC
